name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Analysing the code with lint
      run: |
        npm run lint > linter-log.txt 2>&1
        if [ $? -ne 0 ]; then
           echo "##vso[task.setvariable variable=linterLog]$(cat linter-log.txt | sed '1,/> eslint ./d;/npm ERR!/,$d' | sed '/./,$!d' | sed ':a;N;$!ba;s/\n/%0D%0A/g')"
        fi
      continueOnError: true
      displayName: 'Run Linter'
