name: Static-Analysis

on:
    push:
        branches: [main]
        paths:
            - "contracts/**"
            - ".github/workflows/slither.yml"
    pull_request:
        branches: [main]
        paths:
            - "contracts/**"
            - ".github/workflows/slither.yml"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6]
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Branch name
              run: echo running on branch ${GITHUB_REF##*/}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Slither and dependencies
              run: |
                  sudo snap install solc
                  python -m pip install --upgrade pip
                  pip install slither-analyzer solc-select
                  solc-select install 0.8.2
                  solc-select use 0.8.2
            - name: Summary of static ananlysis
              shell: bash
              run: |
                  echo "Running slither"
                  slither . --exclude-dependencies --exclude-informational --compile-force-framework hardhat --filter-paths=contracts/Base64.sol --exclude=external-function
