name: Test-and-Coverage
defaults:
    run:
        # To load bashrc
        shell: bash -ieo pipefail {0}

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Create env file
              run: |
                  cat << EOF > .env
                  MUMBAI_API_URL=""
                  POLYGON_API_URL=""
                  PRIVATE_KEY="0000000000000000000000000000000000000000000000000000000000000000"
                  POLYSCAN_KEY=""
                  EOF
            - run: npm install
            - run: npm run build
            - run: npm run test
            - run: npm run coverage
